# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_daq.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1296, 640)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        Form.setWindowOpacity(1.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.stopdate = QtWidgets.QDateTimeEdit(self.groupBox)
        self.stopdate.setMaximumSize(QtCore.QSize(300, 16777215))
        self.stopdate.setCalendarPopup(True)
        self.stopdate.setObjectName("stopdate")
        self.gridLayout.addWidget(self.stopdate, 0, 3, 1, 2)
        self.channelpb = QtWidgets.QPushButton(self.groupBox)
        self.channelpb.setObjectName("channelpb")
        self.gridLayout.addWidget(self.channelpb, 2, 0, 1, 1)
        self.stoplabel = QtWidgets.QLabel(self.groupBox)
        self.stoplabel.setObjectName("stoplabel")
        self.gridLayout.addWidget(self.stoplabel, 0, 2, 1, 1)
        self.startlabel = QtWidgets.QLabel(self.groupBox)
        self.startlabel.setObjectName("startlabel")
        self.gridLayout.addWidget(self.startlabel, 0, 0, 1, 1)
        self.startdate = QtWidgets.QDateTimeEdit(self.groupBox)
        self.startdate.setCalendarPopup(True)
        self.startdate.setObjectName("startdate")
        self.gridLayout.addWidget(self.startdate, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)
        self.runlabel = QtWidgets.QLabel(self.groupBox)
        self.runlabel.setObjectName("runlabel")
        self.gridLayout.addWidget(self.runlabel, 1, 0, 1, 1)
        self.browsepb = QtWidgets.QPushButton(self.groupBox)
        self.browsepb.setMaximumSize(QtCore.QSize(100, 16777215))
        self.browsepb.setObjectName("browsepb")
        self.gridLayout.addWidget(self.browsepb, 1, 4, 1, 1)
        self.filenameEdit = QtWidgets.QLineEdit(self.groupBox)
        self.filenameEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.filenameEdit.setObjectName("filenameEdit")
        self.gridLayout.addWidget(self.filenameEdit, 1, 1, 1, 3)
        self.status_text = QtWidgets.QLineEdit(self.groupBox)
        self.status_text.setObjectName("status_text")
        self.gridLayout.addWidget(self.status_text, 2, 2, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.tab)
        self.treeWidget.setTabletTracking(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.gridLayout_3.addWidget(self.treeWidget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setText(0, "1")
        self.gridLayout_2.addWidget(self.treeWidget_2, 2, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.filenameEdit2 = QtWidgets.QLineEdit(self.tab_2)
        self.filenameEdit2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.filenameEdit2.setObjectName("filenameEdit2")
        self.gridLayout_2.addWidget(self.filenameEdit2, 0, 1, 1, 1)
        self.browsepb2 = QtWidgets.QPushButton(self.tab_2)
        self.browsepb2.setObjectName("browsepb2")
        self.gridLayout_2.addWidget(self.browsepb2, 0, 2, 1, 1)
        self.loadcataloguepb = QtWidgets.QPushButton(self.tab_2)
        self.loadcataloguepb.setObjectName("loadcataloguepb")
        self.gridLayout_2.addWidget(self.loadcataloguepb, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DAQ Parser"))
        self.groupBox.setTitle(_translate("Form", "Settings"))
        self.channelpb.setText(_translate("Form", "Get Channel List"))
        self.stoplabel.setText(_translate("Form", "Stop time:"))
        self.startlabel.setText(_translate("Form", "Start time:"))
        self.pushButton.setText(_translate("Form", "Convert to HDF5"))
        self.runlabel.setText(_translate("Form", "Channel description file:"))
        self.browsepb.setText(_translate("Form", "Browse"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "Channel Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "DAQ Parser"))
        self.label.setText(_translate("Form", "Stream:"))
        self.browsepb2.setText(_translate("Form", "Browse"))
        self.loadcataloguepb.setText(_translate("Form", "Load stream catalogue"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Stream Catalogue"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
